package com.example.currencyconverter.utils

enum class Country {
    USA, RUSSIA, ARMENIA, EURO, GEORGIA, RU, AUSTRALIA, AZERBOIJANI, GREAT_BRITIAN,
    BELARUS, BULGARIAN, BRAZIL, HUNGARIAN, VIETNAM, HONGKONG, DAT, ARAB, EGYPT, INDIA, INDONESIA,
    KAZAKHSTAN, CANADA, QATAR, KYRGYZSTAN, CHINA, MOLDOVA, NEW_ZEALAND, NORWAY,
    POLAND, ROMANIA, SINGAPURE, TAJIKISTAN, THAILAND, TURKMENISTAN, TURKEY, UZBEKISTAN, UKRAINE, CZECH,
    SWEDEN, SWITZERLAND, SERBIA, UAR, SOUTH_KOREA, JAPAN;
}